name: app_patinha
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.6
  firebase_core: ^2.29.0
  firebase_storage: ^11.7.1
  cloud_firestore: ^4.16.1
  firebase_auth: ^4.19.1
  image_picker: ^1.0.8
  google_nav_bar: ^5.0.6
  flutter_svg: ^2.0.10+1
  signals_flutter: ^3.0.0
  flutter_getit: ^2.0.0
  fl_chart: ^0.67.0
  intl: ^0.18.1
  shared_preferences: ^2.2.2
  validatorless: ^1.2.3
  asyncstate: ^2.1.1-dev.1
  loading_animation_widget: ^1.2.0+4
  top_snackbar_flutter: ^3.1.0
  flutter_form_builder: ^9.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo-app.png"
  min_sdk_android: 21

  flutter_lints: ^3.0.2

flutter:

  uses-material-design: true


  assets:
    - assets/images/logo-splash.png
    - assets/images/logo-app.png
    - assets/images/profile.png
    - assets/images/dog.svg
    - assets/images/logo-escuro.svg
    - assets/images/logo-claro.svg
    - assets/images/logo-horizontal.svg
    - assets/images/navigation.svg
    - assets/images/icon.svg
    - assets/images/developers.svg
    - assets/images/post.svg
    - assets/images/help.svg
    
  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/font/Montserrat-Thin.ttf
          weight: 100
        - asset: assets/font/Montserrat-ThinItalic.ttf
          style: italic
          weight: 100
        - asset: assets/font/Montserrat-ExtraLight.ttf
          weight: 200
        - asset: assets/font/Montserrat-ExtraLightItalic.ttf
          style: italic
          weight: 200
        - asset: assets/font/Montserrat-Light.ttf
          weight: 300
        - asset: assets/font/Montserrat-LightItalic.ttf
          style: italic
          weight: 300
        - asset: assets/font/Montserrat-Regular.ttf
          weight: 400
        - asset: assets/font/Montserrat-Italic.ttf
          style: italic
          weight: 400
        - asset: assets/font/Montserrat-Medium.ttf
          weight: 500
        - asset: assets/font/Montserrat-MediumItalic.ttf
          style: italic
          weight: 500
        - asset: assets/font/Montserrat-SemiBold.ttf
          weight: 600
        - asset: assets/font/Montserrat-SemiBoldItalic.ttf
          style: italic
          weight: 600
        - asset: assets/font/Montserrat-Bold.ttf
          weight: 700
        - asset: assets/font/Montserrat-BoldItalic.ttf
          style: italic
          weight: 700
        - asset: assets/font/Montserrat-ExtraBold.ttf
          weight: 800
        - asset: assets/font/Montserrat-ExtraBoldItalic.ttf
          style: italic
          weight: 800
        - asset: assets/font/Montserrat-Black.ttf
          weight: 900
        - asset: assets/font/Montserrat-BlackItalic.ttf
          style: italic
          weight: 900